name: medula
description: A Dart library for machine learning algorithms making it easy for Flutter Developers to write custom machine learning systems inside the mobile app itself.
version: 0.0.2
homepage: https://github.com/rshrc/medula
author: Team Medula <rishieric91@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"
